name: publish package to Github Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: macos-13
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '15'
          registry-url: 'https://npm.pkg.github.com
      
      - run: npm install
      - run: npm run build
      - name: Login to GitHub Package Registry
        run: echo "@lonelypaprika:registry=https://npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Publish Package
        run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
